# Generated by Django 2.2.8 on 2019-12-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='sensor_1',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='point',
            name='sensor_2',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='point',
            name='sensor_3',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='point',
            name='sensor_4',
            field=models.FloatField(default=None),
        ),
    ]
