# Generated by Django 2.2.8 on 2019-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191217_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='sensor_1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='sensor_2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='sensor_3',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='sensor_4',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
