# Generated by Django 2.2.8 on 2019-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191217_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='sensor_1',
        ),
        migrations.RemoveField(
            model_name='point',
            name='sensor_2',
        ),
        migrations.RemoveField(
            model_name='point',
            name='sensor_3',
        ),
        migrations.RemoveField(
            model_name='point',
            name='sensor_4',
        ),
        migrations.AddField(
            model_name='point',
            name='sensor',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
