# Generated by Django 2.2.8 on 2020-01-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191217_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='sensor',
            new_name='sensor_id',
        ),
    ]
